version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    restart: always
    environment:
      - PYTHON_API_URL=http://api:5000
    depends_on:
      - api

  api:
    build:
      context: ./python-service
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./src/app/models:/app/models
